{
    "name": "Radiology Backend",
    "version": "1.0",
    "summary": "Backend module for Radiology Flutter App",
    "author": "Mohamed Saoud",
    "depends": ["base", "website", "portal", "auth_signup"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        'views/config.xml',
        'views/hospital_views.xml',
        'views/radiologist_views.xml',
        'views/missions_views.xml',
        'views/application_views.xml',
        'views/menu.xml',
        'views/radiolink_portal_layout.xml',
        "views/radiologist_profile_portal.xml",
        'views/hospital_signup_templates.xml',
        'views/portal_missions.xml',
        'views/portal_mission_new.xml',
        'views/portal_radiologists_templates.xml',
        'views/portal_mission_details.xml',
        'views/portal_chat.xml',
        'views/portal_chat_room.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'radiology/static/src/js/portal_chat.js',
            'radiology/static/src/scss/portal_chat.scss',
        ],
    },
    "installable": True,
    "application": True,
}
