{
    "name": "Radiology Backend",
    "version": "1.0",
    "summary": "Backend module for Radiology Flutter App",
    "author": "Mohamed Saoud",
    "depends": ["base", "website", "portal", "auth_signup", "base_setup"],
    "data": [
        "data/website_demo_menu.xml",
        "data/demo_booking_mail_template.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        'views/config.xml',
        'views/hospital_views.xml',
        'views/radiologist_views.xml',
        'views/missions_views.xml',
        'views/application_views.xml',
        'views/notification_views.xml',
        'views/suspicious_message_views.xml',
        'views/demo_booking_views.xml',
        'views/menu.xml',
        'views/radiolink_portal_layout.xml',
        "views/radiologist_profile_portal.xml",
        'views/hospital_signup_templates.xml',
        'views/reserve_demo_templates.xml',
        'views/website_header.xml',
        'views/website_homepage.xml',
        'views/website_pricing.xml',
        'views/portal_missions.xml',
        'views/portal_mission_new.xml',
        'views/portal_radiologists_templates.xml',
        'views/portal_mission_details.xml',
        'views/portal_chat.xml',
        'views/portal_chat_room.xml',
        'views/login.xml',
        'views/my_home.xml',
        'views/portal_favoris.xml',
        'views/portal_my_missions.xml',
        'views/dashboard.xml',
        'views/report_mission_template.xml',
        'views/report_mission.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'radiology/static/src/scss/website_header.scss',
            'radiology/static/src/scss/radiolink_demo.scss',
            'radiology/static/src/scss/radiolink_missions.scss',
            'radiology/static/src/scss/radiolink_home.scss',
            'radiology/static/src/scss/radiovac_home.scss',
            'radiology/static/src/scss/radiovac_portal.scss',
            'radiology/static/src/js/header_messages.js',
            'radiology/static/src/js/portal_chat.js',
            'radiology/static/src/js/mission_match_modal.js',
            'radiology/static/src/js/radiovac_page_transition.js',
            'radiology/static/src/js/radiolink_demo.js',
            'radiology/static/src/scss/portal_chat.scss',
        ],
    },
    "installable": True,
    "application": True,
}
